-- ═══════════════════════════════════════════════════════════════════════
-- SEED 02 — Catálogo de exercícios do sistema (138 exercícios)
--
-- Todos com created_by = NULL (exercício do sistema) e is_public = true.
-- Idempotente: o índice único uq_exercises_system_slug garante que rodar
-- de novo não duplica.
--
-- Distribuição: peito 16 · costas 17 · ombros 14 · bíceps 10 · tríceps 10
--               antebraço 4 · trapézio 4 · quadríceps 14 · posterior 7
--               glúteos 6 · panturrilha 5 · abdômen 14 · lombar 4
--               corpo inteiro 13
-- ═══════════════════════════════════════════════════════════════════════

insert into public.exercises
  (name_pt, name_en, slug, primary_muscle_group_id, equipment_id, mechanic,
   force_type, difficulty, tracking_type, is_unilateral, instructions)
select
  v.name_pt, v.name_en, v.slug, mg.id, eq.id,
  v.mechanic::exercise_mechanic,
  v.force::force_type,
  v.diff::experience_level,
  v.track::tracking_type,
  v.unilateral,
  v.instructions
from (values

-- ─────────────────────────────────────────────────────────────── PEITO (16)
('Supino Reto com Barra','Barbell Bench Press','supino-reto-barra','chest','barbell','compound','push','intermediate','weight_reps',false,
 array['Deite no banco com os pés firmes no chão e as escápulas retraídas.','Segure a barra um pouco além da largura dos ombros.','Desça controlando até a linha do peito.','Empurre até estender os cotovelos sem travá-los.']),
('Supino Reto com Halteres','Dumbbell Bench Press','supino-reto-halteres','chest','dumbbell','compound','push','beginner','weight_reps',false,
 array['Deite com um halter em cada mão na altura do peito.','Empurre os halteres para cima até quase encostarem.','Desça controlando até sentir alongamento no peito.']),
('Supino Inclinado com Barra','Incline Barbell Press','supino-inclinado-barra','chest','barbell','compound','push','intermediate','weight_reps',false,
 array['Ajuste o banco entre 30° e 45°.','Desça a barra até a parte alta do peito.','Empurre de volta mantendo os punhos alinhados.']),
('Supino Inclinado com Halteres','Incline Dumbbell Press','supino-inclinado-halteres','chest','dumbbell','compound','push','intermediate','weight_reps',false,
 array['Banco entre 30° e 45°, halteres na altura do peito.','Empurre para cima e levemente para dentro.','Desça controlando até alongar o peitoral.']),
('Supino Declinado com Barra','Decline Barbell Press','supino-declinado-barra','chest','barbell','compound','push','intermediate','weight_reps',false,
 array['Banco declinado com as pernas travadas.','Desça a barra até a parte baixa do peito.','Empurre de volta sem travar os cotovelos.']),
('Supino na Máquina','Machine Chest Press','supino-maquina','chest','machine','compound','push','beginner','weight_reps',false,
 array['Ajuste o banco para as pegadas ficarem na altura do peito.','Empurre até quase estender os cotovelos.','Retorne controlando o peso.']),
('Supino no Smith','Smith Machine Bench Press','supino-smith','chest','smith','compound','push','beginner','weight_reps',false,
 array['Posicione o banco sob a barra do Smith.','Destrave a barra e desça até o peito.','Empurre de volta e trave ao final da série.']),
('Crucifixo Reto com Halteres','Dumbbell Fly','crucifixo-reto-halteres','chest','dumbbell','isolation','push','beginner','weight_reps',false,
 array['Deitado, braços abertos com cotovelos levemente flexionados.','Abra até sentir o alongamento do peitoral.','Feche em arco, sem transformar em supino.']),
('Crucifixo Inclinado com Halteres','Incline Dumbbell Fly','crucifixo-inclinado-halteres','chest','dumbbell','isolation','push','beginner','weight_reps',false,
 array['Banco a 30°, halteres acima do peito.','Abra os braços em arco mantendo os cotovelos fixos.','Retorne contraindo o peitoral.']),
('Crossover na Polia','Cable Crossover','crossover-polia','chest','cable','isolation','push','beginner','weight_reps',false,
 array['Polias na altura dos ombros, um pé à frente.','Traga as mãos para a frente do corpo em arco.','Contraia no centro e retorne controlando.']),
('Peck Deck (Voador)','Pec Deck','peck-deck','chest','machine','isolation','push','beginner','weight_reps',false,
 array['Costas apoiadas, cotovelos na altura dos ombros.','Feche os braços à frente contraindo o peito.','Abra controlando até sentir alongamento.']),
('Flexão de Braço','Push-up','flexao-braco','chest','bodyweight','compound','push','beginner','reps_only',false,
 array['Mãos um pouco além da largura dos ombros.','Mantenha o corpo alinhado da cabeça aos pés.','Desça até o peito quase encostar e empurre de volta.']),
('Flexão de Braço Inclinada','Incline Push-up','flexao-inclinada','chest','bodyweight','compound','push','beginner','reps_only',false,
 array['Apoie as mãos em um banco ou superfície elevada.','Desça o peito em direção ao apoio.','Empurre de volta mantendo o corpo reto.']),
('Flexão de Braço Declinada','Decline Push-up','flexao-declinada','chest','bodyweight','compound','push','intermediate','reps_only',false,
 array['Pés apoiados em um banco, mãos no chão.','Desça o peito em direção ao chão.','Empurre de volta sem deixar o quadril cair.']),
('Mergulho nas Paralelas','Chest Dip','mergulho-paralelas','chest','bodyweight','compound','push','advanced','reps_only',false,
 array['Apoie-se nas barras paralelas com os braços estendidos.','Incline o tronco à frente e desça até 90° de cotovelo.','Empurre de volta contraindo o peitoral.']),
('Pullover com Halter','Dumbbell Pullover','pullover-halter','chest','dumbbell','isolation','pull','intermediate','weight_reps',false,
 array['Deitado no banco, segure um halter acima do peito.','Leve o halter para trás da cabeça em arco.','Retorne contraindo peitoral e dorsal.']),

-- ────────────────────────────────────────────────────────────── COSTAS (17)
('Barra Fixa (Pegada Pronada)','Pull-up','barra-fixa','back','pullup_bar','compound','pull','advanced','reps_only',false,
 array['Pegada pronada, mãos além da largura dos ombros.','Puxe até o queixo passar da barra.','Desça controlando até estender os braços.']),
('Barra Fixa Supinada','Chin-up','barra-fixa-supinada','back','pullup_bar','compound','pull','advanced','reps_only',false,
 array['Pegada supinada na largura dos ombros.','Puxe até o peito se aproximar da barra.','Desça controlando.']),
('Puxada Frontal (Pulley)','Lat Pulldown','puxada-frontal','back','machine','compound','pull','beginner','weight_reps',false,
 array['Pegada aberta, coxas travadas no apoio.','Puxe a barra até a parte alta do peito.','Retorne controlando sem soltar a tensão.']),
('Puxada Supinada','Underhand Pulldown','puxada-supinada','back','machine','compound','pull','beginner','weight_reps',false,
 array['Pegada supinada na largura dos ombros.','Puxe a barra até o peito aproximando as escápulas.','Retorne controlando.']),
('Puxada com Triângulo','Close-grip Pulldown','puxada-triangulo','back','machine','compound','pull','beginner','weight_reps',false,
 array['Use o pegador triângulo com as mãos juntas.','Puxe até a altura do esterno.','Retorne alongando bem o dorsal.']),
('Remada Curvada com Barra','Barbell Row','remada-curvada-barra','back','barbell','compound','pull','intermediate','weight_reps',false,
 array['Incline o tronco cerca de 45° com a coluna neutra.','Puxe a barra em direção ao umbigo.','Desça controlando sem arredondar as costas.']),
('Remada Curvada Supinada','Underhand Barbell Row','remada-curvada-supinada','back','barbell','compound','pull','intermediate','weight_reps',false,
 array['Pegada supinada, tronco inclinado.','Puxe a barra até a parte baixa do abdômen.','Retorne controlando.']),
('Remada Unilateral com Halter (Serrote)','One-arm Dumbbell Row','remada-serrote','back','dumbbell','compound','pull','beginner','weight_reps',true,
 array['Apoie um joelho e uma mão no banco.','Puxe o halter em direção ao quadril.','Desça alongando o dorsal. Repita do outro lado.']),
('Remada Baixa na Polia','Seated Cable Row','remada-baixa-polia','back','cable','compound','pull','beginner','weight_reps',false,
 array['Sentado, joelhos levemente flexionados, coluna neutra.','Puxe o pegador até o abdômen aproximando as escápulas.','Retorne alongando sem curvar as costas.']),
('Remada Cavalinho (T-Bar)','T-Bar Row','remada-cavalinho','back','barbell','compound','pull','intermediate','weight_reps',false,
 array['Tronco inclinado, peito apoiado ou livre.','Puxe a barra em direção ao abdômen.','Desça controlando o peso.']),
('Remada na Máquina','Machine Row','remada-maquina','back','machine','compound','pull','beginner','weight_reps',false,
 array['Peito apoiado no encosto.','Puxe os pegadores para trás juntando as escápulas.','Retorne controlando.']),
('Remada Curvada com Halteres','Bent-over Dumbbell Row','remada-halteres-bilateral','back','dumbbell','compound','pull','beginner','weight_reps',false,
 array['Tronco inclinado, um halter em cada mão.','Puxe os dois halteres em direção ao quadril.','Desça controlando.']),
('Pulldown com Braços Estendidos','Straight-arm Pulldown','pulldown-bracos-estendidos','back','cable','isolation','pull','beginner','weight_reps',false,
 array['Em pé à frente da polia alta, braços estendidos.','Puxe a barra até as coxas mantendo os cotovelos fixos.','Retorne controlando.']),
('Pullover na Polia','Cable Pullover','pullover-polia','back','cable','isolation','pull','intermediate','weight_reps',false,
 array['Polia alta, braços estendidos à frente.','Puxe em arco até as coxas contraindo o dorsal.','Retorne alongando.']),
('Levantamento Terra','Deadlift','levantamento-terra','back','barbell','compound','pull','advanced','weight_reps',false,
 array['Pés na largura do quadril, barra rente à canela.','Coluna neutra, peito aberto, quadril acima dos joelhos.','Empurre o chão e estenda quadril e joelhos juntos.','Desça controlando pelo mesmo caminho.']),
('Remada Invertida','Inverted Row','remada-invertida','back','bodyweight','compound','pull','beginner','reps_only',false,
 array['Deite sob uma barra fixa baixa e segure-a.','Mantenha o corpo reto e puxe o peito até a barra.','Desça controlando.']),
('Puxada Unilateral na Polia','Single-arm Lat Pulldown','puxada-unilateral-polia','back','cable','compound','pull','intermediate','weight_reps',true,
 array['Segure a polia alta com uma das mãos.','Puxe até o cotovelo passar da linha do tronco.','Retorne alongando. Repita do outro lado.']),

-- ────────────────────────────────────────────────────────────── OMBROS (14)
('Desenvolvimento Militar com Barra','Overhead Press','desenvolvimento-militar-barra','shoulders','barbell','compound','push','intermediate','weight_reps',false,
 array['Em pé, barra na altura das clavículas.','Empurre acima da cabeça sem arquear a lombar.','Desça controlando até a posição inicial.']),
('Desenvolvimento com Halteres','Dumbbell Shoulder Press','desenvolvimento-halteres','shoulders','dumbbell','compound','push','beginner','weight_reps',false,
 array['Sentado com as costas apoiadas, halteres na altura das orelhas.','Empurre acima da cabeça sem travar os cotovelos.','Desça controlando.']),
('Desenvolvimento Arnold','Arnold Press','desenvolvimento-arnold','shoulders','dumbbell','compound','push','intermediate','weight_reps',false,
 array['Comece com as palmas voltadas para você.','Gire os punhos enquanto empurra para cima.','Retorne fazendo o caminho inverso.']),
('Desenvolvimento na Máquina','Machine Shoulder Press','desenvolvimento-maquina','shoulders','machine','compound','push','beginner','weight_reps',false,
 array['Ajuste o banco para as pegadas ficarem na altura dos ombros.','Empurre acima da cabeça.','Retorne controlando.']),
('Desenvolvimento no Smith','Smith Shoulder Press','desenvolvimento-smith','shoulders','smith','compound','push','beginner','weight_reps',false,
 array['Banco sob a barra do Smith, barra na altura do queixo.','Empurre acima da cabeça.','Desça controlando até o queixo.']),
('Elevação Lateral com Halteres','Dumbbell Lateral Raise','elevacao-lateral-halteres','shoulders','dumbbell','isolation','push','beginner','weight_reps',false,
 array['Braços ao lado do corpo, cotovelos levemente flexionados.','Eleve até a altura dos ombros.','Desça controlando, sem embalo.']),
('Elevação Lateral na Polia','Cable Lateral Raise','elevacao-lateral-polia','shoulders','cable','isolation','push','beginner','weight_reps',true,
 array['Polia baixa, pegador na mão oposta.','Eleve o braço lateralmente até a altura do ombro.','Desça controlando. Repita do outro lado.']),
('Elevação Lateral na Máquina','Machine Lateral Raise','elevacao-lateral-maquina','shoulders','machine','isolation','push','beginner','weight_reps',false,
 array['Cotovelos apoiados nos suportes.','Eleve até a altura dos ombros.','Desça controlando.']),
('Elevação Frontal com Halteres','Front Raise','elevacao-frontal-halteres','shoulders','dumbbell','isolation','push','beginner','weight_reps',false,
 array['Halteres à frente das coxas.','Eleve os braços à frente até a altura dos ombros.','Desça controlando.']),
('Elevação Frontal com Barra','Barbell Front Raise','elevacao-frontal-barra','shoulders','barbell','isolation','push','beginner','weight_reps',false,
 array['Barra à frente das coxas, pegada pronada.','Eleve até a altura dos ombros.','Desça controlando sem usar o tronco.']),
('Crucifixo Inverso com Halteres','Reverse Fly','crucifixo-inverso-halteres','shoulders','dumbbell','isolation','pull','beginner','weight_reps',false,
 array['Tronco inclinado à frente, halteres pendurados.','Abra os braços lateralmente até a altura dos ombros.','Retorne controlando.']),
('Crucifixo Inverso na Máquina','Reverse Pec Deck','crucifixo-inverso-maquina','shoulders','machine','isolation','pull','beginner','weight_reps',false,
 array['Peito apoiado no encosto, braços à frente.','Abra os braços para trás juntando as escápulas.','Retorne controlando.']),
('Face Pull','Face Pull','face-pull','shoulders','cable','isolation','pull','intermediate','weight_reps',false,
 array['Corda na polia alta, na altura do rosto.','Puxe em direção à testa, abrindo os cotovelos.','Retorne controlando.']),
('Elevação Lateral Inclinada','Incline Lateral Raise','elevacao-lateral-inclinada','shoulders','dumbbell','isolation','push','intermediate','weight_reps',true,
 array['Deite de lado em um banco inclinado.','Eleve o halter lateralmente até a vertical.','Desça controlando. Repita do outro lado.']),

-- ────────────────────────────────────────────────────────────── BÍCEPS (10)
('Rosca Direta com Barra','Barbell Curl','rosca-direta-barra','biceps','barbell','isolation','pull','beginner','weight_reps',false,
 array['Em pé, cotovelos fixos ao lado do tronco.','Flexione até a contração máxima.','Desça controlando até estender os braços.']),
('Rosca Direta com Barra W','EZ-bar Curl','rosca-direta-barra-w','biceps','barbell','isolation','pull','beginner','weight_reps',false,
 array['Segure a barra W na pegada angulada.','Flexione os cotovelos sem mover os ombros.','Desça controlando.']),
('Rosca Alternada com Halteres','Alternating Dumbbell Curl','rosca-alternada','biceps','dumbbell','isolation','pull','beginner','weight_reps',true,
 array['Halteres ao lado do corpo, palmas para dentro.','Flexione um braço girando o punho para cima.','Desça e alterne os lados.']),
('Rosca Martelo','Hammer Curl','rosca-martelo','biceps','dumbbell','isolation','pull','beginner','weight_reps',false,
 array['Halteres com as palmas voltadas para dentro.','Flexione mantendo a pegada neutra.','Desça controlando.']),
('Rosca Concentrada','Concentration Curl','rosca-concentrada','biceps','dumbbell','isolation','pull','beginner','weight_reps',true,
 array['Sentado, cotovelo apoiado na parte interna da coxa.','Flexione o cotovelo até a contração máxima.','Desça controlando. Repita do outro lado.']),
('Rosca Scott','Preacher Curl','rosca-scott','biceps','barbell','isolation','pull','intermediate','weight_reps',false,
 array['Braços apoiados no banco Scott.','Flexione até a contração máxima.','Desça até quase estender, sem soltar a tensão.']),
('Rosca na Polia','Cable Curl','rosca-polia','biceps','cable','isolation','pull','beginner','weight_reps',false,
 array['Polia baixa, cotovelos junto ao tronco.','Flexione até a contração máxima.','Retorne controlando.']),
('Rosca Inclinada com Halteres','Incline Dumbbell Curl','rosca-inclinada','biceps','dumbbell','isolation','pull','intermediate','weight_reps',false,
 array['Sentado em banco inclinado, braços pendurados.','Flexione sem mover os ombros à frente.','Desça alongando bem o bíceps.']),
('Rosca 21','21s Curl','rosca-21','biceps','barbell','isolation','pull','advanced','weight_reps',false,
 array['7 repetições na metade inferior do movimento.','7 repetições na metade superior.','7 repetições completas, sem descanso entre as partes.']),
('Rosca Inversa','Reverse Curl','rosca-inversa','biceps','barbell','isolation','pull','intermediate','weight_reps',false,
 array['Pegada pronada na barra.','Flexione os cotovelos mantendo os punhos firmes.','Desça controlando.']),

-- ───────────────────────────────────────────────────────────── TRÍCEPS (10)
('Tríceps na Polia com Corda','Rope Pushdown','triceps-polia-corda','triceps','cable','isolation','push','beginner','weight_reps',false,
 array['Cotovelos junto ao corpo, corda na polia alta.','Estenda os cotovelos abrindo a corda no final.','Retorne controlando.']),
('Tríceps na Polia com Barra','Bar Pushdown','triceps-polia-barra','triceps','cable','isolation','push','beginner','weight_reps',false,
 array['Cotovelos fixos ao lado do tronco.','Estenda os cotovelos até o final do movimento.','Retorne controlando.']),
('Tríceps Testa com Barra W','EZ-bar Skull Crusher','triceps-testa-barra-w','triceps','barbell','isolation','push','intermediate','weight_reps',false,
 array['Deitado, barra acima da testa.','Flexione apenas os cotovelos, descendo a barra.','Estenda de volta sem mover os ombros.']),
('Tríceps Testa com Halteres','Dumbbell Skull Crusher','triceps-testa-halteres','triceps','dumbbell','isolation','push','intermediate','weight_reps',false,
 array['Deitado, halteres acima do peito.','Flexione os cotovelos levando os halteres às orelhas.','Estenda de volta.']),
('Tríceps Francês','Overhead Dumbbell Extension','triceps-frances','triceps','dumbbell','isolation','push','intermediate','weight_reps',true,
 array['Halter acima da cabeça com um braço.','Flexione o cotovelo levando o halter atrás da cabeça.','Estenda de volta. Repita do outro lado.']),
('Tríceps Coice','Triceps Kickback','triceps-coice','triceps','dumbbell','isolation','push','beginner','weight_reps',true,
 array['Tronco inclinado, cotovelo na altura do tronco.','Estenda o cotovelo para trás.','Retorne controlando. Repita do outro lado.']),
('Mergulho no Banco','Bench Dip','mergulho-banco','triceps','bodyweight','compound','push','beginner','reps_only',false,
 array['Mãos apoiadas no banco atrás do corpo.','Desça flexionando os cotovelos até 90°.','Empurre de volta.']),
('Supino Fechado','Close-grip Bench Press','supino-fechado','triceps','barbell','compound','push','intermediate','weight_reps',false,
 array['Pegada na largura dos ombros.','Desça a barra mantendo os cotovelos junto ao corpo.','Empurre de volta.']),
('Tríceps na Máquina','Machine Triceps Extension','triceps-maquina','triceps','machine','isolation','push','beginner','weight_reps',false,
 array['Ajuste o assento e apoie os cotovelos.','Estenda os cotovelos completamente.','Retorne controlando.']),
('Extensão de Tríceps Acima da Cabeça na Polia','Overhead Cable Extension','triceps-acima-cabeca-polia','triceps','cable','isolation','push','intermediate','weight_reps',false,
 array['De costas para a polia, corda acima da cabeça.','Estenda os cotovelos à frente.','Retorne alongando o tríceps.']),

-- ─────────────────────────────────────────────────────────── ANTEBRAÇO (4)
('Rosca de Punho com Barra','Wrist Curl','rosca-punho','forearms','barbell','isolation','pull','beginner','weight_reps',false,
 array['Antebraços apoiados no banco, palmas para cima.','Flexione apenas os punhos.','Desça controlando.']),
('Rosca de Punho Inversa','Reverse Wrist Curl','rosca-punho-inversa','forearms','barbell','isolation','pull','beginner','weight_reps',false,
 array['Antebraços apoiados, palmas para baixo.','Estenda os punhos para cima.','Desça controlando.']),
('Farmer''s Walk','Farmer''s Walk','farmers-walk','forearms','dumbbell','compound','static','intermediate','weight_duration',false,
 array['Segure um halter pesado em cada mão.','Caminhe com o tronco ereto e ombros para trás.','Mantenha pelo tempo determinado.']),
('Rolo de Punho','Wrist Roller','rolo-punho','forearms','other','isolation','pull','intermediate','duration',false,
 array['Segure o rolo à frente com os braços estendidos.','Enrole a corda girando os punhos.','Desenrole controlando.']),

-- ──────────────────────────────────────────────────────────── TRAPÉZIO (4)
('Encolhimento com Barra','Barbell Shrug','encolhimento-barra','trapezius','barbell','isolation','pull','beginner','weight_reps',false,
 array['Barra à frente das coxas, braços estendidos.','Eleve os ombros em direção às orelhas.','Desça controlando.']),
('Encolhimento com Halteres','Dumbbell Shrug','encolhimento-halteres','trapezius','dumbbell','isolation','pull','beginner','weight_reps',false,
 array['Halteres ao lado do corpo.','Eleve os ombros o máximo possível.','Desça controlando.']),
('Remada Alta com Barra','Upright Row','remada-alta-barra','trapezius','barbell','compound','pull','intermediate','weight_reps',false,
 array['Pegada pronada na largura dos ombros.','Puxe a barra até a altura do peito, cotovelos acima.','Desça controlando.']),
('Encolhimento no Smith','Smith Shrug','encolhimento-smith','trapezius','smith','isolation','pull','beginner','weight_reps',false,
 array['Barra do Smith à frente das coxas.','Eleve os ombros mantendo os braços estendidos.','Desça controlando.']),

-- ───────────────────────────────────────────────────────── QUADRÍCEPS (14)
('Agachamento Livre','Barbell Back Squat','agachamento-livre','quadriceps','barbell','compound','push','advanced','weight_reps',false,
 array['Barra apoiada no trapézio, pés na largura dos ombros.','Desça flexionando quadril e joelhos até as coxas ficarem paralelas.','Suba empurrando o chão, mantendo o tronco firme.']),
('Agachamento Frontal','Front Squat','agachamento-frontal','quadriceps','barbell','compound','push','advanced','weight_reps',false,
 array['Barra apoiada à frente, sobre os deltoides.','Cotovelos altos, desça mantendo o tronco ereto.','Suba empurrando o chão.']),
('Agachamento no Smith','Smith Squat','agachamento-smith','quadriceps','smith','compound','push','beginner','weight_reps',false,
 array['Barra no trapézio, pés ligeiramente à frente.','Desça até as coxas ficarem paralelas.','Suba controlando.']),
('Agachamento Búlgaro','Bulgarian Split Squat','agachamento-bulgaro','quadriceps','dumbbell','compound','push','intermediate','weight_reps',true,
 array['Pé de trás apoiado em um banco.','Desça até o joelho da frente formar 90°.','Suba empurrando o calcanhar da frente. Troque de perna.']),
('Agachamento Goblet','Goblet Squat','agachamento-goblet','quadriceps','dumbbell','compound','push','beginner','weight_reps',false,
 array['Segure um halter junto ao peito.','Desça mantendo o tronco ereto.','Suba empurrando o chão.']),
('Agachamento Sumô','Sumo Squat','agachamento-sumo','quadriceps','barbell','compound','push','intermediate','weight_reps',false,
 array['Pés bem afastados, pontas viradas para fora.','Desça mantendo os joelhos alinhados com os pés.','Suba contraindo glúteos e coxas.']),
('Agachamento com Halteres','Dumbbell Squat','agachamento-halteres','quadriceps','dumbbell','compound','push','beginner','weight_reps',false,
 array['Um halter em cada mão ao lado do corpo.','Desça até as coxas ficarem paralelas.','Suba empurrando o chão.']),
('Leg Press 45°','45° Leg Press','leg-press-45','quadriceps','machine','compound','push','beginner','weight_reps',false,
 array['Pés na plataforma, na largura dos ombros.','Desça até cerca de 90° de flexão do joelho.','Empurre sem travar os joelhos no topo.']),
('Leg Press Horizontal','Horizontal Leg Press','leg-press-horizontal','quadriceps','machine','compound','push','beginner','weight_reps',false,
 array['Ajuste o encosto e apoie os pés na plataforma.','Desça controlando até 90°.','Empurre de volta.']),
('Hack Machine','Hack Squat','hack-machine','quadriceps','machine','compound','push','intermediate','weight_reps',false,
 array['Costas apoiadas, pés na plataforma.','Desça até as coxas ficarem paralelas.','Suba empurrando com os calcanhares.']),
('Cadeira Extensora','Leg Extension','cadeira-extensora','quadriceps','machine','isolation','push','beginner','weight_reps',false,
 array['Ajuste o encosto e o apoio dos tornozelos.','Estenda os joelhos até a contração máxima.','Desça controlando.']),
('Afundo com Halteres','Dumbbell Lunge','afundo-halteres','quadriceps','dumbbell','compound','push','intermediate','weight_reps',true,
 array['Dê um passo à frente com um halter em cada mão.','Desça até o joelho de trás quase encostar no chão.','Volte à posição inicial. Alterne as pernas.']),
('Passada (Walking Lunge)','Walking Lunge','passada-halteres','quadriceps','dumbbell','compound','push','intermediate','weight_reps',false,
 array['Halteres ao lado do corpo.','Dê passos largos alternando as pernas, descendo a cada passo.','Mantenha o tronco ereto.']),
('Step-up no Banco','Step-up','step-up','quadriceps','dumbbell','compound','push','beginner','weight_reps',true,
 array['Suba em um banco apoiando o pé inteiro.','Estenda o quadril no topo.','Desça controlando. Repita com a outra perna.']),

-- ────────────────────────────────────────────── POSTERIOR DE COXA (7)
('Levantamento Terra Romeno','Romanian Deadlift','terra-romeno','hamstrings','barbell','compound','pull','intermediate','weight_reps',false,
 array['Barra à frente das coxas, joelhos levemente flexionados.','Empurre o quadril para trás descendo a barra rente às pernas.','Suba contraindo glúteos e posteriores.']),
('Stiff com Barra','Stiff-leg Deadlift','stiff-barra','hamstrings','barbell','compound','pull','intermediate','weight_reps',false,
 array['Pernas quase estendidas, coluna neutra.','Desça a barra até sentir alongamento no posterior.','Suba contraindo glúteos.']),
('Stiff com Halteres','Dumbbell Stiff-leg Deadlift','stiff-halteres','hamstrings','dumbbell','compound','pull','beginner','weight_reps',false,
 array['Halteres à frente das coxas.','Empurre o quadril para trás descendo os halteres.','Suba contraindo o posterior.']),
('Mesa Flexora','Lying Leg Curl','mesa-flexora','hamstrings','machine','isolation','pull','beginner','weight_reps',false,
 array['Deitado, apoio dos tornozelos ajustado.','Flexione os joelhos até a contração máxima.','Desça controlando.']),
('Cadeira Flexora (Sentado)','Seated Leg Curl','cadeira-flexora','hamstrings','machine','isolation','pull','beginner','weight_reps',false,
 array['Sentado, apoio sobre os tornozelos.','Flexione os joelhos puxando para baixo.','Retorne controlando.']),
('Good Morning','Good Morning','good-morning','hamstrings','barbell','compound','pull','advanced','weight_reps',false,
 array['Barra apoiada no trapézio, joelhos levemente flexionados.','Incline o tronco à frente empurrando o quadril para trás.','Volte contraindo glúteos e posteriores.']),
('Flexora Nórdica','Nordic Curl','flexora-nordica','hamstrings','bodyweight','compound','pull','advanced','reps_only',false,
 array['Ajoelhado com os tornozelos presos.','Desça o tronco à frente resistindo com o posterior.','Retorne à posição inicial.']),

-- ─────────────────────────────────────────────────────────── GLÚTEOS (6)
('Elevação Pélvica (Hip Thrust)','Hip Thrust','elevacao-pelvica','glutes','barbell','compound','push','intermediate','weight_reps',false,
 array['Costas apoiadas no banco, barra sobre o quadril.','Eleve o quadril até a extensão completa.','Desça controlando sem encostar totalmente.']),
('Ponte de Glúteo','Glute Bridge','ponte-gluteo','glutes','bodyweight','compound','push','beginner','reps_only',false,
 array['Deitado, joelhos flexionados e pés no chão.','Eleve o quadril contraindo os glúteos.','Desça controlando.']),
('Glúteo na Polia (Kickback)','Cable Kickback','gluteo-polia','glutes','cable','isolation','push','beginner','weight_reps',true,
 array['Tornozeleira presa à polia baixa.','Estenda a perna para trás contraindo o glúteo.','Retorne controlando. Repita do outro lado.']),
('Coice na Máquina','Machine Glute Kickback','gluteo-maquina','glutes','machine','isolation','push','beginner','weight_reps',true,
 array['Apoie o tronco e posicione o pé na plataforma.','Empurre para trás estendendo o quadril.','Retorne controlando. Repita do outro lado.']),
('Abdução de Quadril na Máquina','Hip Abduction Machine','abducao-quadril-maquina','glutes','machine','isolation','push','beginner','weight_reps',false,
 array['Sentado com as pernas nos apoios.','Abra as pernas contraindo os glúteos.','Retorne controlando.']),
('Abdução de Quadril com Elástico','Banded Hip Abduction','abducao-quadril-elastico','glutes','band','isolation','push','beginner','reps_only',false,
 array['Elástico acima dos joelhos.','Abra as pernas contra a resistência.','Retorne controlando.']),

-- ────────────────────────────────────────────────────── PANTURRILHA (5)
('Panturrilha em Pé na Máquina','Standing Calf Raise','panturrilha-em-pe','calves','machine','isolation','push','beginner','weight_reps',false,
 array['Ombros sob os apoios, pontas dos pés na plataforma.','Eleve os calcanhares o máximo possível.','Desça alongando a panturrilha.']),
('Panturrilha Sentado','Seated Calf Raise','panturrilha-sentado','calves','machine','isolation','push','beginner','weight_reps',false,
 array['Joelhos sob os apoios, pontas dos pés na plataforma.','Eleve os calcanhares contraindo.','Desça alongando.']),
('Panturrilha no Leg Press','Leg Press Calf Raise','panturrilha-leg-press','calves','machine','isolation','push','beginner','weight_reps',false,
 array['Pontas dos pés na borda da plataforma.','Empurre estendendo os tornozelos.','Retorne alongando.']),
('Panturrilha em Pé com Halteres','Dumbbell Calf Raise','panturrilha-halteres','calves','dumbbell','isolation','push','beginner','weight_reps',false,
 array['Halteres ao lado do corpo, pontas dos pés elevadas.','Eleve os calcanhares.','Desça alongando.']),
('Panturrilha Unilateral','Single-leg Calf Raise','panturrilha-unilateral','calves','bodyweight','isolation','push','beginner','reps_only',true,
 array['Apoie-se em uma perna sobre um degrau.','Eleve o calcanhar o máximo possível.','Desça alongando. Repita do outro lado.']),

-- ───────────────────────────────────────────────────────── ABDÔMEN (14)
('Prancha','Plank','prancha','abs','bodyweight','isolation','static','beginner','duration',false,
 array['Apoie antebraços e pontas dos pés.','Mantenha o corpo alinhado, sem elevar ou afundar o quadril.','Sustente pelo tempo determinado.']),
('Prancha Lateral','Side Plank','prancha-lateral','abs','bodyweight','isolation','static','intermediate','duration',true,
 array['Apoie um antebraço e a lateral do pé.','Eleve o quadril mantendo o corpo alinhado.','Sustente e repita do outro lado.']),
('Abdominal Supra (Crunch)','Crunch','abdominal-supra','abs','bodyweight','isolation','pull','beginner','reps_only',false,
 array['Deitado, joelhos flexionados.','Eleve o tronco contraindo o abdômen.','Desça controlando sem encostar a cabeça.']),
('Abdominal Infra (Elevação de Pernas)','Lying Leg Raise','abdominal-infra','abs','bodyweight','isolation','pull','beginner','reps_only',false,
 array['Deitado, pernas estendidas.','Eleve as pernas até a vertical sem tirar a lombar do chão.','Desça controlando.']),
('Elevação de Pernas na Barra','Hanging Leg Raise','elevacao-pernas-barra','abs','pullup_bar','isolation','pull','advanced','reps_only',false,
 array['Pendurado na barra fixa.','Eleve as pernas até a altura do quadril ou acima.','Desça controlando, sem balançar.']),
('Abdominal na Polia','Cable Crunch','abdominal-polia','abs','cable','isolation','pull','intermediate','weight_reps',false,
 array['Ajoelhado de frente para a polia alta, corda junto à cabeça.','Flexione o tronco contraindo o abdômen.','Retorne controlando.']),
('Abdominal na Máquina','Machine Crunch','abdominal-maquina','abs','machine','isolation','pull','beginner','weight_reps',false,
 array['Ajuste o assento e segure os apoios.','Flexione o tronco contraindo o abdômen.','Retorne controlando.']),
('Abdominal Bicicleta','Bicycle Crunch','abdominal-bicicleta','abs','bodyweight','isolation','pull','beginner','reps_only',false,
 array['Deitado, mãos atrás da cabeça.','Leve o cotovelo ao joelho oposto alternando os lados.','Mantenha o ritmo controlado.']),
('Russian Twist','Russian Twist','russian-twist','abs','plate','isolation','pull','intermediate','reps_only',false,
 array['Sentado com o tronco inclinado, segurando uma anilha.','Gire o tronco de um lado ao outro.','Mantenha o abdômen contraído.']),
('Roda Abdominal (Ab Wheel)','Ab Wheel Rollout','ab-wheel','abs','other','compound','pull','advanced','reps_only',false,
 array['Ajoelhado, segurando a roda à frente.','Role para a frente mantendo o abdômen firme.','Volte sem deixar a lombar arquear.']),
('Mountain Climber','Mountain Climber','mountain-climber','abs','bodyweight','compound','push','beginner','duration',false,
 array['Posição de prancha alta.','Traga os joelhos ao peito alternadamente.','Mantenha o ritmo pelo tempo determinado.']),
('Hollow Hold','Hollow Hold','hollow-hold','abs','bodyweight','isolation','static','intermediate','duration',false,
 array['Deitado, eleve pernas e ombros do chão.','Mantenha a lombar colada no chão.','Sustente pelo tempo determinado.']),
('Abdominal Oblíquo','Oblique Crunch','abdominal-obliquo','abs','bodyweight','isolation','pull','beginner','reps_only',false,
 array['Deitado com as pernas caídas para um lado.','Eleve o tronco contraindo o oblíquo.','Repita do outro lado.']),
('Prancha com Elevação de Perna','Plank with Leg Lift','prancha-elevacao','abs','bodyweight','isolation','static','intermediate','duration',false,
 array['Posição de prancha nos antebraços.','Eleve uma perna sem mover o quadril.','Alterne as pernas durante o tempo.']),

-- ──────────────────────────────────────────────────────────── LOMBAR (4)
('Hiperextensão Lombar','Back Extension','hiperextensao-lombar','lower_back','bodyweight','isolation','pull','beginner','reps_only',false,
 array['Quadril apoiado no banco romano.','Desça o tronco e suba até a linha do corpo.','Não hiperestenda a coluna no topo.']),
('Extensão Lombar na Máquina','Machine Back Extension','extensao-lombar-maquina','lower_back','machine','isolation','pull','beginner','weight_reps',false,
 array['Costas apoiadas no encosto móvel.','Estenda o tronco para trás.','Retorne controlando.']),
('Bird Dog','Bird Dog','bird-dog','lower_back','bodyweight','isolation','static','beginner','reps_only',false,
 array['Apoiado nas mãos e joelhos.','Estenda o braço e a perna opostos ao mesmo tempo.','Retorne e alterne os lados.']),
('Superman','Superman','superman','lower_back','bodyweight','isolation','static','beginner','duration',false,
 array['Deitado de bruços, braços estendidos à frente.','Eleve braços, peito e pernas do chão.','Sustente pelo tempo determinado.']),

-- ───────────────────────────────────────────────────── CORPO INTEIRO (13)
('Burpee','Burpee','burpee','full_body','bodyweight','compound','push','intermediate','reps_only',false,
 array['Agache e apoie as mãos no chão.','Jogue as pernas para trás e faça uma flexão.','Volte e salte com os braços acima da cabeça.']),
('Thruster','Thruster','thruster','full_body','barbell','compound','push','advanced','weight_reps',false,
 array['Barra na altura das clavículas, agache.','Suba explodindo e empurre a barra acima da cabeça.','Retorne à posição inicial.']),
('Clean and Press','Clean and Press','clean-and-press','full_body','barbell','compound','push','advanced','weight_reps',false,
 array['Puxe a barra do chão até os ombros.','Empurre acima da cabeça em um movimento contínuo.','Retorne controlando.']),
('Kettlebell Swing','Kettlebell Swing','kettlebell-swing','full_body','kettlebell','compound','pull','intermediate','reps_only',false,
 array['Kettlebell entre as pernas, quadril para trás.','Impulsione com o quadril até a altura do peito.','Deixe o peso voltar entre as pernas.']),
('Snatch com Halter','Dumbbell Snatch','snatch-halter','full_body','dumbbell','compound','pull','advanced','weight_reps',true,
 array['Halter no chão entre os pés.','Puxe explosivamente até acima da cabeça em um movimento.','Desça controlando. Repita do outro lado.']),
('Corda Naval (Battle Rope)','Battle Rope','battle-rope','full_body','other','compound','pull','intermediate','duration',false,
 array['Segure uma ponta da corda em cada mão.','Faça ondas alternadas com os braços.','Mantenha pelo tempo determinado.']),
('Remo Ergômetro','Rowing Machine','remo-ergometro','full_body','machine','compound','pull','beginner','distance_duration',false,
 array['Empurre com as pernas primeiro.','Puxe o cabo até a base do peito.','Retorne na ordem inversa.']),
('Esteira (Corrida)','Treadmill Run','esteira-corrida','full_body','machine','compound','push','beginner','distance_duration',false,
 array['Ajuste velocidade e inclinação.','Mantenha o ritmo pelo tempo ou distância planejada.']),
('Esteira (Caminhada Inclinada)','Incline Treadmill Walk','esteira-caminhada','full_body','machine','compound','push','beginner','distance_duration',false,
 array['Ajuste a inclinação entre 8% e 15%.','Caminhe sem se apoiar nas barras laterais.']),
('Bicicleta Ergométrica','Stationary Bike','bicicleta-ergometrica','full_body','machine','compound','push','beginner','distance_duration',false,
 array['Ajuste a altura do banco à altura do quadril.','Pedale mantendo a cadência planejada.']),
('Elíptico','Elliptical','eliptico','full_body','machine','compound','push','beginner','distance_duration',false,
 array['Apoie os pés nos pedais e segure as alavancas.','Mantenha o movimento contínuo pelo tempo determinado.']),
('Pular Corda','Jump Rope','pular-corda','full_body','other','compound','push','beginner','duration',false,
 array['Corda no tamanho certo para a sua altura.','Salte com os pés juntos girando pelos punhos.','Mantenha pelo tempo determinado.']),
('Escada Ergométrica','Stair Climber','escada-ergometrica','full_body','machine','compound','push','intermediate','duration',false,
 array['Suba os degraus mantendo o tronco ereto.','Evite se apoiar totalmente nas barras laterais.'])

) as v(name_pt, name_en, slug, mg_slug, eq_slug, mechanic, force, diff, track, unilateral, instructions)
join public.muscle_groups mg on mg.slug = v.mg_slug
join public.equipment     eq on eq.slug = v.eq_slug
on conflict do nothing;


-- ═══════════════════════════════════════════════════════════════════════
-- Músculos secundários dos principais exercícios compostos
-- (usado na tela de detalhe do exercício)
-- ═══════════════════════════════════════════════════════════════════════
insert into public.exercise_muscle_groups (exercise_id, muscle_group_id, role)
select e.id, mg.id, 'secondary'::muscle_role
from (values
  ('supino-reto-barra','triceps'),          ('supino-reto-barra','shoulders'),
  ('supino-reto-halteres','triceps'),       ('supino-reto-halteres','shoulders'),
  ('supino-inclinado-barra','shoulders'),   ('supino-inclinado-barra','triceps'),
  ('supino-inclinado-halteres','shoulders'),('supino-inclinado-halteres','triceps'),
  ('supino-fechado','chest'),               ('supino-fechado','shoulders'),
  ('flexao-braco','triceps'),               ('flexao-braco','shoulders'),
  ('mergulho-paralelas','triceps'),         ('mergulho-paralelas','shoulders'),
  ('barra-fixa','biceps'),                  ('barra-fixa','forearms'),
  ('barra-fixa-supinada','biceps'),
  ('puxada-frontal','biceps'),
  ('remada-curvada-barra','biceps'),        ('remada-curvada-barra','lower_back'),
  ('remada-serrote','biceps'),
  ('remada-baixa-polia','biceps'),
  ('levantamento-terra','hamstrings'),      ('levantamento-terra','glutes'),
  ('levantamento-terra','lower_back'),      ('levantamento-terra','trapezius'),
  ('desenvolvimento-militar-barra','triceps'),
  ('desenvolvimento-halteres','triceps'),
  ('desenvolvimento-arnold','triceps'),
  ('remada-alta-barra','shoulders'),
  ('agachamento-livre','glutes'),           ('agachamento-livre','hamstrings'),
  ('agachamento-livre','lower_back'),
  ('agachamento-frontal','glutes'),         ('agachamento-frontal','abs'),
  ('agachamento-bulgaro','glutes'),
  ('agachamento-goblet','glutes'),
  ('leg-press-45','glutes'),
  ('afundo-halteres','glutes'),
  ('terra-romeno','glutes'),                ('terra-romeno','lower_back'),
  ('stiff-barra','glutes'),                 ('stiff-barra','lower_back'),
  ('good-morning','glutes'),                ('good-morning','lower_back'),
  ('elevacao-pelvica','hamstrings'),
  ('kettlebell-swing','glutes'),            ('kettlebell-swing','hamstrings'),
  ('thruster','quadriceps'),                ('thruster','shoulders'),
  ('clean-and-press','shoulders'),          ('clean-and-press','quadriceps'),
  ('burpee','chest'),                       ('burpee','quadriceps'),
  ('farmers-walk','trapezius'),
  ('ab-wheel','shoulders'),
  ('mountain-climber','shoulders')
) as v(ex_slug, mg_slug)
join public.exercises     e  on e.slug = v.ex_slug and e.created_by is null
join public.muscle_groups mg on mg.slug = v.mg_slug
on conflict (exercise_id, muscle_group_id) do nothing;
